import Isobel from "../../assets/Isobel.png";
import Andy from "../../assets/Andy.png";
import Sarina from "../../assets/Sarina.png";
import Katie from "../../assets/Katie.png";
import Caitlin from "../../assets/Caitlin.png";
import Courtney from "../../assets/Courtney.png";
import Kira from "../../assets/Kira.png";
import Joslyn from "../../assets/Joslyn.png";

export const therapistsData = [
  {
    id: "t1",
    position: "LAMFT",
    shortDescription: "Licensed Associate Marriage and Family Therapist",
    name: "Isobel Mannino",
    pronouns: "She/Her",
    location: "Pennsylvania",
    payment: "Insurance & Private Pay",
    traits: ["Compassionate", "Cheerful"],
    about: [
      "Fluent in Emotion-Focused, Narrative, CBT, and Solution-Focused Therapy. I help individuals and couples tackle trauma, anxiety, life transitions, grief, and high-conflict situations (yes, even those never-ending arguments).",
      "Specializing in breaking toxic patterns and boosting emotional and sexual intimacy—let’s get you unstuck and connected.",
      "Therapy with me? Think: compassionate, no judgment, real talk—with a little humor and a lot of support.",
      "Ready to turn obstacles into growth? Let’s chat.",
    ],

    specialties: [
      "Trauma",
      "Anxiety",
      "Infidelity",
      "Relational Issues",
      "Relationships",
      "Dating",
    ],
    fees: {individual: 130, couples: 155},
    image: Isobel,
  },
  {
    id: "t2",
    position: "MHC Intern",
    shortDescription: "Student Mental Health Counselor Intern",
    name: "Andy Fuentes",
    pronouns: "He/Him",
    location: "Florida",
    payment: "Insurance & Private Pay",
    traits: ["Balanced", "Non-judgmental"],
    about: [
      "Therapy style: collaborative, client-centered, and all about you.",
      "I blend CBT, mindfulness, and solution-focused techniques to help you manage anxiety, depression, relationship stuff, ADHD, burnout, and more—with a side of self-discovery and personal growth.",
      "I’m into exploring masculinity, work-life balance, grief, and spiritual questions—all while creating a safe, judgment-free zone.",
      "Think of me as your co-pilot for navigating life’s chaos, uncovering strengths, and building healthier ways to cope.",
      "Let’s figure it out together—one mindful step at a time.",
    ],
    specialties: [
      "Anxiety",
      "Mindfulness",
      "Depression",
      "Self-Awareness",
      "Relational Issues",
      "ADHD",
    ],
    fees: {individual: 90, couples: 105},
    image: Andy,
  },
  {
    id: "t3",
    position: "MHC Intern",
    shortDescription: "Student Mental Health Counselor Intern",
    name: "Sarina Abramowitz",
    pronouns: "She/Her",
    location: "Florida",
    payment: "Insurance & Private Pay",
    traits: ["Supportive", "Cheerful"],
    about: [
      "Here to help you break free from anxiety, depression, trauma, and relationship struggles—one step at a time.",
      "I use CBT and ACT to help you ditch the mental roadblocks, stay present, and build the life (and relationships) you actually want.",
      "Miami native with a passion for self-growth, real connection, and meeting you where you are.",
      "My style? Supportive, non-judgmental, and all about creating a space where you feel seen, heard, and empowered.",
      "Ready to turn challenges into growth? Let’s make it happen.",
    ],
    specialties: ["Anxiety", "Trauma", "Depression"],
    fees: {individual: 90, couples: 105},
    image: Sarina,
  },
  {
    id: "t4",
    position: "Licensed Psychologist",
    shortDescription: "Licensed Psychologist",
    name: "Katie Manganello",
    pronouns: "She/Her",
    location: "Florida, Pennsylvania",
    payment: "Insurance & Private Pay",
    traits: ["Compassionate", "Cheerful"],
    about: [
      "Helping people kick OCD, anxiety, and PTSD to the curb is kind of my thing.",
      "Based in Delaware and Pennsylvania, I mix science-backed tools like CBT, ACT, and Exposure Therapy with a whole lot of compassion (and maybe a little humor) to help you feel like you again.",
      "I get it—finding the right therapist can feel like dating… but way more stressful.",
      "My goal? To make therapy feel less intimidating and more like a team effort. We’ll set real goals, tackle the tough stuff together, and celebrate the wins—big or small.",
      "Let’s get you unstuck and moving forward—on your terms.",
    ],
    specialties: [
      "Anxiety",
      "Trauma",
      "PTSD",
      "Self-Awareness",
      "Social Anxiety Disorder",
      "OCD",
    ],
    fees: {individual: 250},
    image: Katie,
  },
  {
    id: "t5",
    position: "LAMFT",
    shortDescription: "Licensed Associate Marriage and Family Therapist",
    name: "Caitlin Harrison",
    pronouns: "She/Her",
    location: "Florida",
    payment: "Insurance & Private Pay",
    traits: ["Compassionate", "Expert in relationships therapy"],
    about: [
      "Idaho native turned Pennsylvania therapist, I’m here for individuals and couples navigating anxiety, trauma, relationship struggles—and the big, messy stuff in between.",
      "I’m all about creating a space where you feel safe, seen, and truly understood.",
      "Special interests? Religious trauma, deconstruction, and the journey of redefining your beliefs and identity. We’ll unpack those layers together, no judgment—just support, clarity, and space to grow.",
      "I also offer EMDR for when talk therapy isn’t quite cutting it—and for couples, I help break toxic cycles and rebuild emotional (and intimate) connections that last.",
      "Let’s do the deep work—and maybe even laugh a little along the way.",
    ],
    specialties: [
      "Anxiety",
      "Boundaries",
      "Depression",
      "Attachment Styles",
      "Communication Issues",
      "Dating",
      "Relational Issues",
    ],
    fees: {individual: 130, couples: 155},
    image: Caitlin,
  },
  {
    id: "t6",
    position: "LAMFT",
    shortDescription: "Licensed Associate Marriage and Family Therapist",
    name: "Courtney Burkhardt",
    pronouns: "She/Her",
    location: "Philadelphia",
    payment: "Insurance & Private Pay",
    traits: ["Flexible", "LGBTQIA+ community"],
    about: [
      "Philadelphia-based therapist with a sex therapy twist—I help individuals and couples navigate love, intimacy, and all the life stuff that can get in the way.",
      "From major transitions (think: new baby, career shifts, loss) to shifting family dynamics or rebuilding connection, I’m here for the real, messy, human moments.",
      "My style? Flexible, collaborative, and low-pressure.",
      "Whether you’re exploring emotional or sexual intimacy, LGBTQIA+ or CNM relationships, or just figuring you out—I create a space that’s supportive, judgment-free, and tailored to your vibe.",
      "Let’s find your flow again—together.",
    ],
    specialties: [
      "Anxiety",
      "Boundaries",
      "Depression",
      "Attachment Styles",
      "Communication Issues",
      "Dating",
      "Relational Issues",
      "Trauma",
    ],
    fees: {individual: 130, couples: 155},
    image: Courtney,
  },
  {
    id: "t7",
    position: "LAMFT",
    shortDescription: "Licensed Associate Marriage and Family Therapist",
    name: "Kira Yakubov Ploshansky",
    pronouns: "She/Her",
    location: "Philadelphia",
    payment: "Insurance & Private Pay",
    traits: ["Flexible", "LGBTQIA+ community"],
    about: [
      "Therapist, podcast host, ADHD-er, and founder of Heal Your Roots Wellness—nice to meet you!",
      "I help individuals and couples cut through anxiety, improve communication, and build deeper, more connected relationships.",
      "Whether we’re working through relationship patterns, neurodivergence, or just life’s chaos, I bring compassion, real talk, and a few laughs along the way.",
      "I’m also the voice behind the Heal Your Roots Podcast and author of The Deeper Connecting Couple’s Workbook (bonus points if you love a good workbook).",
      "Born in the former Soviet Union, raised in Philly, now soaking up sunshine in Florida.",
      "I bring cultural sensitivity, evidence-based strategies, and a big heart to every session.",
      "Let’s get real, get curious, and help you feel more empowered, understood, and connected.",
    ],
    specialties: [
      "Anxiety",
      "Boundaries",
      "Depression",
      "Attachment Styles",
      "Communication Issues",
      "Dating",
      "Relational Issues",
      "Trauma",
    ],
    fees: {individual: 130, couples: 155},
    image: Kira,
  },
  {
    id: "t8",
    position: "LAMFT",
    shortDescription: "Licensed Associate Marriage and Family Therapist",
    name: "Joslyn Justi",
    pronouns: "She/Her",
    location: "Philadelphia",
    payment: "Insurance & Private Pay",
    traits: ["Supportive", "Life transitions"],
    about: [
      "Anxiety wrangler. Relationship pattern decoder.",
      "I’m all about helping individuals and couples feel more connected—both to themselves and each other.",
      "My vibe? Supportive, non-judgmental, and big on building trust so we can do the deep work and celebrate your wins.",
      "I specialize in anxiety, OCD, perfectionism, and life transitions—basically, if your brain is running a mile a minute or your relationship feels stuck, I’ve got you.",
      "I help clients shift from “over-care” to true care, build emotional safety, and create new, healthier patterns.",
      "Let’s be real: life is messy, and we all need a little grace.",
      "Therapy with me is about learning, healing, and finding your footing—with a good mix of mindfulness, self-awareness, and maybe a few laughs along the way.",
    ],
    specialties: [
      "Anxiety",
      "Boundaries",
      "Depression",
      "Anger",
      "Attachment Styles",
      "Communication Issues",
      "Dating",
      "Relational Issues",
    ],
    fees: {individual: "Not accepting clients"},
    image: Joslyn,
  },
];
